---
date: "2017-10-17T15:26:15Z"
draft: false
title: Monsters
---

> ### Zombie
>
>*Medium undead, neutral evil*
>
> - **Armor Class** 8
> - **Hit Points** 22 (3d8 + 9)
> - **Speed** 20 ft.
>
> | STR | DEX | CON | INT  |WIS | CHA |
> |---|---|:---:|:---:|:---:|:---:|
> |13 (+1)|6 (-2)|16 (+3)|3 (-4)|6 (-2)|5 (-3)|
>
> - **Condition Immunities** poisoned
> - **Senses** darkvision 60 ft., passive Perception 8
> - **Languages** understands the languages it knew in life but can't speak
- **Challenge** 1/4 (50 XP)
<!-- > -->
> ***Undead Fortitude.*** If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5+the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.
>
> #### Actions
>
> ***Slam.*** _Melee Weapon Attack:_ +3 to hit, reach 5 ft., one target. _Hit:_ 4 (1d6 + 1) bludgeoning damage.

___

> ### Dire Wolf
>
>*Large beast, unaligned*
>
> - **Armor Class** 14 (natural armor)
> - **Hit Points** 37 (5d10 + 10)
> - **Speed** 50 ft.
>
> |STR|DEX|CON|INT|WIS|CHA|
> |:---:|:---:|:---:|:---:|:---:|:---:|
> |17 (+3)|15 (+2)|15 (+2)|3 (-4)|12 (+1)|7 (-2)|
>
> - **Skills** Perception +3, Stealth +4
> - **Senses** passive Perception 13
> - **Languages** —
> - **Challenge** 1 (200 XP)
>
> ***Keen Hearing and Smell.*** The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.
>
> ***Pack Tactics.*** The wolf has advantage on an attack roll against a creature if at least one of the wolf's allies is within 5 ft. of the creature and the ally isn't incapacitated.
>
> #### Actions
>
> ***Bite.*** _Melee Weapon Attack:_ +5 to hit, reach 5 ft., one target. _Hit:_ 10 (2d6 + 3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.