---
date: "2017-10-17T15:26:15Z"
draft: false
title: The Farm
---

You rub the sleep from your eyes, it still must be late because it's dark outside. Unsure of what woke you, you turn over and look around your small room. Everything appears normal except you notice a faint orange light flickering in from underneath your door. You catch a scent of smoke, but before you can register it, you hear a horrifying noise from the yard. The panicked squealing of pigs makes your heart pound.

As you step outside, the scene before you is difficult to comprehend. Your humble barn is ablaze, flames ripping through the thatched roof, anything once living in there would certainly be dead, but there are no pigs in sight, and you no longer hear their squeals. In fact, things have gone eerily quiet since you stepped out into the dark.

As your eyes adjust to the flames, you notice a shadowy humanoid figure just beyond the edge of your pasture. The light from the blaze seems to disappear into this shade, it is completely black, and you can't make out any of its features.

You feel heat emanating from above and behind you. The last thing you hear is a loud crack before the world around you goes dark.
